services:
  manager-api:
    build: .
    container_name: vm-manager-api
    extra_hosts:
      - "guacamole.lilepiserver.duckdns.org:192.168.10.101"
    environment:
      - PROXMOX_API_URL=${PROXMOX_API_URL}
      - PROXMOX_API_USER=${PROXMOX_API_USER}
      - PROXMOX_API_TOKEN_ID=${PROXMOX_API_TOKEN_ID}
      - PROXMOX_API_TOKEN_SECRET=${PROXMOX_API_TOKEN_SECRET}
      - PROXMOX_TLS_INSECURE=${PROXMOX_TLS_INSECURE}
      - PYTHONHTTPSVERIFY=${PYTHONHTTPSVERIFY}
      - GUACAMOLE_URL=${GUACAMOLE_URL}
      - GUACAMOLE_API_USER=${GUACAMOLE_API_USER}
      - GUACAMOLE_API_PASSWORD=${GUACAMOLE_API_PASSWORD}
      - DATABASE_SOURCE=${DATABASE_SOURCE}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
