---
- name: Deploy VMs to Proxmox
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add vm to the inventory
      ansible.builtin.lineinfile:
        path: ../ansible/inventory.ini
        create: true
        mode: '0644'
        regexp: '^vm_{{ vmid }}\s'
        line: 'vm_{{ vmid }} ansible_host={{ ip }} vmid={{ vmid }}'
        insertafter: '^\[student_containers\]'

    - name: Create VM {{ vmid }}
      community.proxmox.proxmox:
        api_host: "{{ lookup('env', 'PROXMOX_API_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
        vmid: "{{ vmid }}"
        hostname: "{{ name }}"
        node: "pve"
        validate_certs: false
        cpus: 2
        memory: 2048
        swap: 512
        unprivileged: true
        disk_volume:
          storage: "local-lvm"
          size: 8
        netif:
          net0: "name=eth0,gw=192.168.10.1,ip={{ ip }}/24,bridge=vmbr0"
        ostemplate: "local:vztmpl/debian-13-standard_13.6-1_amd64.tar.zst"
        pubkey: "{{ lookup('file', '/root/.ssh/id_ed25519.pub') | trim }}"
        state: present
        onboot: true
        cmode: 'tty'

    - name: Start VM {{ vmid }}
      community.proxmox.proxmox:
        api_host: "{{ lookup('env', 'PROXMOX_API_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
        vmid: "{{ vmid }}"
        validate_certs: false
        state: started
        timeout: 90
