---
- name: Deploy VMs to Proxmox
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Check if inventory file exists
      ansible.builtin.stat:
        path: ../ansible/inventory.ini
      register: inventory_file

    - name: Create initial inventory file if missing
      ansible.builtin.copy:
        dest: ../ansible/inventory.ini
        mode: '0644'
        content: |
          [student_containers]

          [student_containers:vars]
          ansible_user=root
          ansible_ssh_private_key_file=/root/.ssh/id_ed25519
          ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      when: not inventory_file.stat.exists
  
    - name: Add vm to the inventory
      ansible.builtin.lineinfile:
        path: ../ansible/inventory.ini
        create: true
        mode: '0644'
        regexp: '^vm_{{ vmid }}\s'
        line: 'vm_{{ vmid }} ansible_host={{ ip }} vmid={{ vmid }}'
        insertafter: '^\[student_containers\]'

    - name: Clone Cloud-Init Template to VM {{ vmid }}
      community.proxmox.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
        newid: "{{ vmid }}"
        name: "{{ vm_name }}"
        node: "pve"
        validate_certs: false
        
        # Clone from your Proxmox Template ID
        clone: debian-13-cloudinit-template
        vmid: 9000
        full: true
        
        # Hardware spec overrides
        cores: 2
        memory: 2048
        
        # Cloud-Init configuration
        ide:
          ide2: 'local:cloudinit,format=qcow2'
        ipconfig:
          ipconfig0: "ip={{ ip }}/24,gw=192.168.10.1"
        sshkeys: "{{ lookup('file', '/root/.ssh/id_ed25519.pub') | trim }}"

        api_timeout: 500
        timeout: 500
        state: present

    - name: Start VM {{ vmid }}
      community.proxmox.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
        vmid: "{{ vmid }}"
        validate_certs: false
        state: started
        api_timeout: 500
        timeout: 500



