---
- name: Hot edit Proxmox VM & Manage users
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    node_name: "pve"

  tasks:
    - name: Update Proxmox VM Name (Hot Edit)
      community.proxmox.proxmox:
        api_host: "{{ lookup('env', 'PROXMOX_API_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
        vmid: "{{ target_vmid }}"
        node: "{{ node_name }}"
        hostname: "{{ new_team_name }}"
        state: present

- name: Apply student changes inside target VM
  hosts: "vm_{{ target_vmid }}"
  become: true
  tasks:
    - name: Delete old student accounts & home directories
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true
        force: true
      loop: "{{ students_to_remove }}"
      when: students_to_remove | length > 0

    - name: Create new student user accounts
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        groups:
          - groupwork
          - sudo
        append: true
        shell: /bin/bash
        create_home: true
        state: present
      loop: "{{ students_to_add }}"
      when: students_to_add | length > 0
