---
- name: Deploy VMs to Proxmox
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../storage/exports/vars.yml

  tasks:
    - name: Create VMs
      community.proxmox.proxmox:
        api_host: "{{ lookup('env', 'PROXMOX_API_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.name }}"
        node: "pve"
        validate_certs: false
        disk_volume:
          storage: "local-lvm"
          size: 8
        netif:
          net0: "name=eth0,gw=192.168.10.1,ip={{ item.ip }}/24,bridge=vmbr0"
        ostemplate: "local:vztmpl/debian-13-standard_13.6-1_amd64.tar.zst"
        state: present
        onboot: true
        cmode: 'tty'
      loop: "{{ vms }}"

    - name: Start VMs
      community.proxmox.proxmox:
        api_host: "{{ lookup('env', 'PROXMOX_API_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_API_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN_SECRET') }}"
        vmid: "{{ item.vmid }}"
        state: started
        timeout: 90
      loop: "{{ vms }}"